services:
  - type: web
    name: stackoverflowclone
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: APP_BASE_URL
        value: https://stackoverflowclone-amvi.onrender.com
    runtime: docker
